### ISSUE TITLE
FAILED_PRECONDITION probably be 400, not 500

### ISSUE THREAD

**Issue by dansanduleac** [palantir/http-remoting-api#55]
According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412, there is already a "Precondition Failed" HTTP error code.

We're currently [classifying FAILED_PRECONDITION as 500](https://github.com/palantir/http-remoting-api/blob/687932c06b7fae010794432655680abefb0e4249/errors/src/main/java/com/palantir/remoting/api/errors/ErrorType.java#L43).

TBH I realize we're probably going for different semantics than conditional requests which is what 412 serves, however it sounds like it should still belong in the 4xx somehow, since it's semantically closer to INVALID_ARGUMENT (400) than to ILLEGAL_STATE (which doesn't exist but I'd map to 500).

If my understanding is incorrect, I'd love for someone to clarify the reasoning behind this.

**Comment by uschi2000** [comment]
FAILED_PRECONDITION here is interpreted as a server-side issue, not a failed precondition on data passed from a client. For instance, say a server rejects a request because some internal integrity constraint failed, or because a migration hasn't completed yet for a piece of data that was accessed, etc.

**Comment by dansanduleac** [comment]
Ok, I'm guessing this was modelled after [grpc's `FAILED_PRECONDITION`](https://github.com/grpc/grpc-java/blob/03bdb7609eb553b52970b76a220a2775b3184aa3/core/src/main/java/io/grpc/Status.java#L139).
